app:
  host: "0.0.0.0"
  port: 50001
  debug: true
  logfile-path: app.log
  keytab-default-password: @123qwe
  realm: DATALAKE
  webhdfs-url: http://hdm1.datalake.net:14000
  keytab-file-path: /system/keytabs
  keytab-file-local-temp-path: tabs
